#!/bin/bash
kubectl create -f BOXED.yaml
sleep 5
kubectl create -f LDAP.yaml
sleep 5  #wainting for the deployment
bash eos-storage-fst.sh 1 eos-mgm.boxed.svc.cluster.local eos-mgm.boxed.svc.cluster.local  docker default
bash eos-storage-fst.sh 2 eos-mgm.boxed.svc.cluster.local eos-mgm.boxed.svc.cluster.local  docker default
kubectl create -f eos-storage-mgm.yaml 
sleep 5
kubectl create -f eos-storage-fst1.yaml
kubectl create -f eos-storage-fst2.yaml
sleep 5
kubectl create -f CERNBOX.yaml
sleep 10
kubectl create -f SWAN.yaml

kubectl -n boxed get pods -o wide
