#!/bin/bash
kubectl delete -f SWAN.yaml 
sleep 20
kubectl -n boxed get pods -o wide
sleep 20

kubectl delete -f eos-storage-fst2.yaml
kubectl delete -f eos-storage-fst1.yaml
sleep 20

kubectl delete -f eos-storage-mgm.yaml
sleep 20
kubectl delete -f LDAP.yaml 
sleep 20
kubectl delete -f BOXED.yaml
